### ISSUE TITLE
Open-sourcing Offline

### ISSUE THREAD

**Issue by lunaisnotaboy** [offlinedotcom/offlinedotcom#2]
Is there a change Offline could become open-source? I'd like to contribute.

**Comment by offlinedotcom** [comment]
Too early to say. We can collaborate privately if you're open.

**Comment by lunaisnotaboy** [comment]
Yeah!

**Comment by offlinedotcom** [comment]
You can add me on discord. My username is "drhelado."

**Comment by lunaisnotaboy** [comment]
Sent!
